name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo "${{ secrets.DH_PASSWORD }}" | docker login docker.io -u rodrigoaf --password-stdin && docker build . -f Dockerfile -t rodrigoaf/codeeducation:latest && docker push rodrigoaf/codeeducation:latest
