name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DH_PWD: ${{ secrets.DH_PASSWORD }}
      run: docker build . -f Dockerfile -t rodrigoaf/codeeducation:latest && docker login docker.io -u rodrigoaf -p $DH_PWD && docker push rodrigoaf/codeeducation:latest
